# docker-compose.yml - placeholder
# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nami_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nami_hospital
    networks:
      - nami_network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: nami_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=nami_hospital
      - PORT=5000
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - nami_network
    volumes:
      - ./backend:/app

volumes:
  mongodb_data:
    driver: local

networks:
  nami_network:
    driver: bridge


# ---


# Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY backend/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY backend/ .

# Expose port
EXPOSE 5000

# Run the application
CMD ["python", "main.py"]